# -*- coding: utf-8 -*-
"""How the Block A tickets are linked: which services and module builds wait on which.

    python tools/build-ticket-links.py

Reads handoff/service-docs/tasks.csv (build-service-docs.py writes it) and the screen files, and writes
handoff/service-docs/TICKET-LINKS.md: the build layers in order, a service map, every service with what it
waits on and what waits on it, every front-end module with the services its screens need, the reports that
wait for their data, and anything left with no dependency. Run it after tools/refresh.sh; it changes no ticket.
"""
import collections
import csv
import io
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TASKS = ROOT / "handoff" / "service-docs" / "tasks.csv"
OUT = ROOT / "handoff" / "service-docs" / "TICKET-LINKS.md"

rows = list(csv.DictReader(io.open(TASKS, encoding="utf-8")))
by_key = {r["key"]: r for r in rows}
tasks = [r for r in rows if r["type"] == "Task"]
deps = {r["key"]: [d for d in r["dependsOn"].split() if d in by_key] for r in tasks}
needed_by = collections.defaultdict(set)
for k, ds in deps.items():
    for d in ds:
        needed_by[d].add(k)

module_of, app_of = {}, {}
for f in sorted((ROOT / "screens").glob("P*.yaml")):
    doc = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
    app = ((doc.get("platform") or {}).get("name")) or f.stem
    for s in doc.get("screens") or []:
        module_of[s["id"]] = s.get("module") or "Other"
        app_of[s["id"]] = app

SCREEN = re.compile(r"([A-Z]{2,4}-\d{3})$")


def layer(r):
    k, tr = r["key"], r["track"]
    if k.startswith("SETUP-ONBOARD") or tr == "Onboarding":
        return "Onboarding"
    if k.startswith("SETUP-"):
        return "Setup"
    if k.startswith("MIG-") or k.startswith("VM-MIG-") or tr == "Database":
        return "Database"
    if k.startswith(("PLATFORM-", "KERNEL-", "ARCH-", "DB-", "OFFLINE-", "POS-KDS")):
        return "Platform"
    if k.startswith("AI-ENGINE"):
        return "AI engine"
    if tr == "Backend":
        return "Services (Venue Management)" if r["phase"] == "2" else "Services"
    if tr == "Frontend":
        return "Screens (Venue Management)" if r["phase"] == "2" else "Screens"
    return tr or "Other"


def group(r):
    """The service a backend task builds, or the layer name for setup, database and platform."""
    lay = layer(r)
    if lay.startswith("Services"):
        return r["service"].replace("Service", "") or "Other service"
    if lay.startswith("Screens"):
        return "Screens"
    return lay


def module_key(r):
    m = SCREEN.search(r["key"])
    sid = m.group(1) if m else ""
    return (app_of.get(sid, r["platform"] or r["area"]), module_of.get(sid, "Other"))


seq = {r["key"]: int(r["sequence"]) for r in rows}
LAYERS = ["Setup", "Onboarding", "Database", "Platform", "AI engine", "Services", "Screens",
          "Services (Venue Management)", "Screens (Venue Management)"]
out = []
w = out.append
w("# How the Block A tickets are linked\n")
w("> **Generated by** `tools/build-ticket-links.py` from `handoff/service-docs/tasks.csv` (the task sheet that "
  "becomes the OpenProject tickets). A ticket *waits on* another when it cannot be finished before the other is: "
  "that is the \"follows\" link in OpenProject and the order of each person's board.\n")
w(f"**{len(tasks)} tasks, {sum(len(v) for v in deps.values())} links.**\n")

w("## 1. The build layers, in order\n")
w("| Layer | Tasks | Build order | Waits on |")
w("|---|---:|---|---|")
by_layer = collections.defaultdict(list)
for r in tasks:
    by_layer[layer(r)].append(r)
for name in LAYERS + sorted(set(by_layer) - set(LAYERS)):
    rs = by_layer.get(name)
    if not rs:
        continue
    on = collections.Counter(layer(by_key[d]) for r in rs for d in deps[r["key"]] if layer(by_key[d]) != name)
    w(f"| {name} | {len(rs)} | #{min(seq[r['key']] for r in rs)} to #{max(seq[r['key']] for r in rs)} | "
      + (", ".join(f"{k} ({v})" for k, v in on.most_common()) or "nothing") + " |")
w("")

# service-level graph
svc_tasks = collections.defaultdict(list)
for r in tasks:
    if layer(r) in ("Services", "Services (Venue Management)"):
        svc_tasks[group(r)].append(r)
edge = collections.Counter()
for r in tasks:
    g = group(r)
    for d in deps[r["key"]]:
        h = group(by_key[d])
        if g != h and g != "Screens":
            edge[(h, g)] += 1
w("## 2. Service map\n")
w("An arrow means the service on the right waits on the one on the left; the number is how many task links "
  "carry it. Screens are left out here (section 4).\n")
w("```mermaid\nflowchart LR")
node = lambda n: re.sub(r"[^A-Za-z0-9]", "_", n)
for (a, b), n in sorted(edge.items(), key=lambda x: (-x[1], x[0])):
    w(f"  {node(a)}[\"{a}\"] -->|{n}| {node(b)}[\"{b}\"]")
w("```\n")

w("## 3. Services: what each waits on and what waits on it\n")
w("| Service | Owner | Tasks | Points | Build order | Waits on | Needed by |")
w("|---|---|---:|---:|---|---|---|")
for g in sorted(svc_tasks, key=lambda g: min(seq[r["key"]] for r in svc_tasks[g])):
    rs = svc_tasks[g]
    keys = {r["key"] for r in rs}
    on = collections.Counter(group(by_key[d]) for k in keys for d in deps[k] if d not in keys)
    by = collections.Counter()
    for k in keys:
        for n in needed_by[k]:
            if n in keys:
                continue
            rn = by_key[n]
            by["screens: " + module_key(rn)[1] if group(rn) == "Screens" else group(rn)] += 1
    owners = collections.Counter(r["assignee"] for r in rs if r["assignee"])
    pts = sum(int(r["points"] or 0) for r in rs)
    w(f"| **{g}** | {', '.join(o for o, _ in owners.most_common(2))} | {len(rs)} | {pts} | "
      f"#{min(seq[k] for k in keys)} to #{max(seq[k] for k in keys)} | "
      + (", ".join(f"{k} {v}" for k, v in on.most_common()) or "-") + " | "
      + (", ".join(f"{k} {v}" for k, v in by.most_common(6)) + (" ..." if len(by) > 6 else "") or "-") + " |")
w("")

w("## 4. Module builds: the services each module's screens need\n")
w("| App | Module | Screen tasks | Build order | Waits on services | Other |")
w("|---|---|---:|---|---|---|")
mods = collections.defaultdict(list)
for r in tasks:
    if layer(r).startswith("Screens"):
        mods[module_key(r)].append(r)
for (app, mod), rs in sorted(mods.items(), key=lambda x: min(seq[r["key"]] for r in x[1])):
    keys = {r["key"] for r in rs}
    on = collections.Counter(group(by_key[d]) for k in keys for d in deps[k] if d not in keys)
    svc = {k: v for k, v in on.items() if k not in LAYERS and k != "Screens"}
    other = {k: v for k, v in on.items() if k not in svc}
    w(f"| {app} | {mod} | {len(rs)} | #{min(seq[k] for k in keys)} to #{max(seq[k] for k in keys)} | "
      + (", ".join(f"{k} {v}" for k, v in sorted(svc.items(), key=lambda x: -x[1])) or "-") + " | "
      + (", ".join(f"{k} {v}" for k, v in other.items()) or "-") + " |")
w("")

w("## 5. Reports and other read-only work that waits for its data\n")
w("A backend task that only reads waits for the tasks that write what it reads (decided 30 September).\n")
w("| Task | Service | Waits on the data of |")
w("|---|---|---|")
n_rep = 0
for r in sorted(tasks, key=lambda r: seq[r["key"]]):
    if not layer(r).startswith("Services"):
        continue
    feeds = [d for d in deps[r["key"]] if layer(by_key[d]).startswith("Services") and group(by_key[d]) != group(r)]
    if feeds and not any(d.startswith("PLATFORM-IDEMPOTENCY") for d in deps[r["key"]]):
        n_rep += 1
        w(f"| {r['key']} | {group(r)} | " + ", ".join(sorted({group(by_key[d]) for d in feeds})) + " |")
if not n_rep:
    w("| - | - | none |")
w("")

w("## 6. Tasks that wait on nothing\n")
free = [r for r in tasks if not deps[r["key"]]]
w("Only setup and onboarding should be here.\n")
w("| Task | Layer | Build order |")
w("|---|---|---|")
for r in sorted(free, key=lambda r: seq[r["key"]]):
    w(f"| {r['key']} | {layer(r)} | #{seq[r['key']]} |")
w("")

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print(f"ticket links: {len(tasks)} tasks, {sum(len(v) for v in deps.values())} links, "
      f"{len(svc_tasks)} services, {len(mods)} modules -> {OUT.relative_to(ROOT)}")
