// Reads the declared consumer ("which app calls this") column out of
// handoff/api-list.md.
//
// This is the only place in the repo that maps an individual endpoint to a
// front-end app — the contracts carry no `x-ticvai-consumer` extension — and it
// covers a small fraction of the operations. The viewer reports that coverage
// rather than guessing at the rest.

import { readFile, readdir } from 'node:fs/promises';

/**
 * The canonical platform roster is the app list in the frontend monorepo, not
 * whatever happens to be named in the docs — so apps with no declared endpoint
 * still appear, and the gap is visible.
 */
export async function loadPlatforms(root) {
  try {
    const entries = await readdir(`${root}/repos/ticvai-frontend/apps`, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

// Two vocabularies name the same apps and both are live.
//
// The left column is the frontend monorepo's scaffold (`repos/ticvai-frontend/apps`), which
// is what `loadPlatforms` returns. The right is what the package's own screens declare as
// `platform.app`, and what `handoff/api-list.md` has carried since it became generated —
// there are thirteen of those against six of these, so the scaffold is behind the design.
//
// Accepting both keeps the consumer column readable whichever vocabulary it was written in,
// and the mapping folds the package name onto the scaffold name so existing callers are
// unaffected.
const APP_ALIASES = new Map([
  ['guest-web', 'web-b2c'], ['webb2c', 'web-b2c'],
  ['guest-app', 'guest'], ['guest-kiosk', 'kiosk'],
  ['venue-pos', 'pos'],
  ['venue-scanner', 'scanner'],
  ['venue-staff-app', 'employee'],
  ['venue-management-web', 'backoffice'],
  ['ticvai-web', 'backoffice'], ['venue-support-web', 'backoffice'],
  ['developer-portal-web', 'backoffice'], ['signup-web', 'web-b2c'],
  ['partner-web', 'backoffice'], ['accreditation-web', 'backoffice'],
  ['kitchen-display', 'employee'],
]);

const KNOWN_APPS = new Set([
  'pos', 'backoffice', 'scanner', 'guest', 'employee', 'webb2c', 'web-b2c', 'edge', 'kiosk', 'all',
  ...APP_ALIASES.keys(),
]);

/** `/orders/{orderId}/refunds` -> `/orders/{}/refunds` so param names cannot break a match. */
export function normalisePath(urlPath) {
  return urlPath.replace(/\{[^}]*\}/g, '{}').replace(/\/+$/, '');
}

const canonicalApp = (name) => APP_ALIASES.get(name) ?? name;

export async function loadDeclaredConsumers(root) {
  const path = `${root}/handoff/api-list.md`;
  let text;
  try {
    text = await readFile(path, 'utf8');
  } catch {
    return { map: new Map(), apps: [], source: null };
  }

  const map = new Map(); // "GET /orders/{}" -> [apps]
  const apps = new Set();

  // **Read the columns by their heading, not by their position.**
  //
  // This used to index cells 2, 3 and 6, against a table that began with a status column.
  // `api-list.md` became generated on 19 September, the status column went with it — an
  // operation in a contract is published, there is no other state — and an `operation`
  // column took its place. Every row then failed the method test at cell 2 and the map came
  // back empty, which reads exactly like a package with no declared consumers.
  //
  // A heading survives a column moving. The table is regenerated by
  // `tools/build-api-list.py`, and its shape is that tool's business rather than this one's.
  let col = null;
  for (const line of text.split(/\r?\n/)) {
    if (!line.startsWith('|')) continue;
    const cells = line.split('|').map((c) => c.trim());

    if (!col) {
      const head = cells.map((c) => c.toLowerCase().replace(/[^a-z]/g, ''));
      const m = head.indexOf('method');
      const pth = head.indexOf('path');
      const con = head.indexOf('consumers');
      if (m >= 0 && pth >= 0 && con >= 0) col = { method: m, path: pth, consumers: con };
      continue;
    }
    if (cells.length <= col.consumers) continue;

    const method = cells[col.method].toUpperCase();
    if (!/^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)$/.test(method)) continue;

    const urlPath = cells[col.path].replace(/`/g, '').trim();
    if (!urlPath.startsWith('/')) continue;

    const consumers = cells[col.consumers]
      .split(/[,/]/)
      .map((c) => c.trim().toLowerCase())
      .filter((c) => KNOWN_APPS.has(c))
      .map(canonicalApp);

    if (!consumers.length) continue;
    for (const app of consumers) apps.add(app);
    map.set(`${method} ${normalisePath(urlPath)}`, consumers);
  }

  return { map, apps: [...apps].sort(), source: 'handoff/api-list.md' };
}
