// Arabic for the TICVAI mobile app v4 screens. Loaded before ticvai-ar.js, which merges TV_AR_EXTRA.
(function () {
  const A = {
    'Choose a venue app': 'اختر تطبيق المكان', 'Signed in': 'مسجّل الدخول', 'Switch app': 'تبديل التطبيق', 'Live map, ride waits and alerts': 'خريطة مباشرة وأوقات الانتظار والتنبيهات',
    "Don't miss": 'لا تفوّت', 'See all': 'عرض الكل', 'Planner': 'المخطِّط', 'Plan your visit': 'خطّط لزيارتك', 'Six questions, then a plan for each day.': 'ستة أسئلة، ثم خطة لكل يوم.', 'Start planning': 'ابدأ التخطيط',
    'Good to know': 'معلومات مفيدة', 'Explore': 'استكشف', 'Where it is': 'الموقع', 'Buy tickets': 'شراء التذاكر', 'Buy': 'شراء', 'Home': 'الرئيسية', 'Plan': 'خطّط', 'Tickets': 'التذاكر',
    'Not sure? Help me choose': 'محتار؟ ساعدني في الاختيار', 'A few questions, then only the tickets that suit you.': 'بضعة أسئلة، ثم التذاكر التي تناسبك فقط.', 'Book now →': 'احجز الآن ←', 'Show all': 'عرض الكل',
    'Cheapest': 'الأرخص', 'Mid price': 'سعر متوسط', 'Peak price': 'سعر الذروة', 'No sessions match. Try another day or filter.': 'لا توجد جلسات مطابقة. جرّب يومًا أو فلترًا آخر.',
    'Swipe the map sideways to see the whole park.': 'اسحب الخريطة جانبيًا لرؤية المنتزه كاملًا.', 'Call sales': 'اتصل بالمبيعات', 'Email sales': 'راسل المبيعات', '← All categories': '→ كل الفئات',
    'From': 'من', 'To': 'إلى', 'Departures': 'المغادرة', 'Choose…': 'اختر…', 'Drag to turn the stadium. Tap a stand to open its seats.': 'اسحب لتدوير الملعب. اضغط على مدرّج لعرض مقاعده.',
    'Tap or pinch in on a section to see its seats. Green blocks are standing.': 'اضغط أو قرّب على قسم لرؤية مقاعده. المربعات الخضراء للوقوف.', '← Whole map': '→ الخريطة كاملة',
    'Free': 'متاح', 'Yours': 'لك', 'Taken': 'محجوز', 'Pinch out to go back to the full map. Seats are held for 8 minutes.': 'بعّد بإصبعيك للعودة إلى الخريطة كاملة. تُحجز المقاعد لمدة 8 دقائق.',
    'STAGE': 'المسرح', 'Stage': 'المسرح', 'Pitch': 'الملعب', 'PITCH': 'الملعب', 'Sign in': 'تسجيل الدخول', 'Saved guests, cards and member prices': 'الضيوف والبطاقات المحفوظة وأسعار الأعضاء',
    'Continue as a guest': 'المتابعة كضيف', 'Sign in with Apple': 'الدخول عبر Apple', 'Pay with': 'الدفع بواسطة', 'Add to Apple Wallet': 'أضف إلى Apple Wallet',
    'Your plan': 'خطتك', 'Change answers': 'تغيير الإجابات', 'Swap': 'استبدال', 'Remove': 'إزالة', '+ Add something': '+ أضف شيئًا', 'Undo changes': 'تراجع عن التغييرات',
    'Add Fast Track 5': 'أضف المسار السريع 5', 'Book this plan': 'احجز هذه الخطة', 'Your ticket': 'تذكرتك', 'When': 'الموعد', 'Online · answers in seconds': 'متصل · يرد خلال ثوانٍ',
    'Only options that suit everyone in your group are shown.': 'نعرض فقط الخيارات المناسبة لجميع أفراد مجموعتك.', 'Choose': 'اختر', "Everything that suits your group is already in today's plan.": 'كل ما يناسب مجموعتك موجود في خطة اليوم.',
    'Scan a ticket': 'امسح تذكرة', 'Show QR': 'عرض الرمز', 'At the venue · live': 'في المكان · مباشر', 'Waiting times': 'أوقات الانتظار', 'min': 'دقيقة', 'Alerts': 'التنبيهات',
    'Sign in or register': 'الدخول أو التسجيل', 'Choose a destination': 'اختر وجهة', 'Show me these tickets': 'اعرض لي هذه التذاكر', 'Start over': 'ابدأ من جديد',
    'Skip introduction': 'تخطَّ المقدمة', 'Welcome to': 'مرحبًا بك في', 'Start exploring': 'ابدأ الاستكشاف', 'Account': 'الحساب', 'Back': 'رجوع', 'Save': 'حفظ', 'Close': 'إغلاق', 'Fewer': 'أقل', 'More': 'أكثر', 'Send': 'إرسال',
    'Skip the queue with Fast Track': 'تخطَّ الطابور بالمسار السريع', 'Park admission': 'دخول المنتزه', 'Meal combo + park ticket': 'وجبة كومبو مع تذكرة المنتزه', 'Event entry by time slot': 'دخول الفعالية حسب الموعد',
    'Day pass': 'تذكرة يومية', 'Timed session': 'جلسة بموعد', 'Surf session': 'جلسة ركوب الأمواج', 'Cabana for the day': 'كابانا لليوم', 'Match tickets': 'تذاكر المباراة', 'Hospitality': 'الضيافة',
    'Screening': 'عرض سينمائي', 'Reservation': 'حجز', 'Ticketed dinner': 'عشاء بتذكرة', 'Takeaway': 'طلب خارجي', 'Play pass': 'تذكرة لعب', 'Workshop': 'ورشة', 'Party package': 'باقة حفلة',
    'Entry tickets': 'تذاكر الدخول', 'Guided tour': 'جولة مع مرشد', 'Courses': 'الدورات', 'Meeting room': 'غرفة اجتماعات', 'Event': 'فعالية', 'Trip': 'رحلة',
    'Time of day': 'وقت اليوم', 'All day': 'طوال اليوم', 'Morning': 'الصباح', 'Afternoon': 'بعد الظهر', 'Evening': 'المساء',
    'Your ticket is ready': 'تذكرتك جاهزة', 'Offer: 15% off your next visit': 'عرض: خصم 15% على زيارتك القادمة', 'Refund for 2 Jul visit': 'استرداد زيارة 2 يوليو',
    'Two-step sign-in': 'الدخول بخطوتين', 'Face Pass': 'بصمة الوجه', 'Signed-in devices': 'الأجهزة المسجّلة', 'Choose your cabana': 'اختر الكابانا', 'Choose your seats': 'اختر مقاعدك',
    'Add to your visit': 'أضف إلى زيارتك', 'Your details': 'بياناتك', 'Personal details': 'البيانات الشخصية', 'Payment methods': 'طرق الدفع', 'Membership & billing': 'العضوية والفواتير',
    'Data & privacy': 'البيانات والخصوصية', 'Virtual queue': 'الطابور الافتراضي', 'Order food': 'اطلب الطعام', 'Offers': 'العروض', 'Rewards': 'المكافآت', 'Parking': 'المواقف', 'Notifications': 'الإشعارات',
    'Saved': 'المحفوظات', 'Orders & reservations': 'الطلبات والحجوزات', 'Lost & found': 'المفقودات', 'Rate your visit': 'قيّم زيارتك', 'Help & support': 'المساعدة والدعم', 'Accessibility': 'إمكانية الوصول',
    'Search': 'بحث', 'Security & sign-in': 'الأمان وتسجيل الدخول', 'Send a ticket': 'أرسل تذكرة', 'Refund or resell': 'استرداد أو إعادة بيع', 'Add to calendar': 'أضف إلى التقويم',
    'Continue': 'متابعة', 'Continue to payment': 'المتابعة إلى الدفع', 'Choose an option': 'اختر خيارًا', 'View in Tickets': 'عرض في التذاكر', 'Skip': 'تخطَّ',
    'Tap a hut on the park map. Grey huts are taken.': 'اضغط على كوخ في خريطة المنتزه. الأكواخ الرمادية محجوزة.', 'Stalls, circle and balcony on one plan. Tap a seat to hold it.': 'الصالة والدائرة والشرفة في مخطط واحد. اضغط على مقعد لحجزه.',
    'Pick a section, then your seats. Pinch in on the map to zoom.': 'اختر قسمًا ثم مقاعدك. قرّب بإصبعيك للتكبير.', 'Nothing else to fill in unless this activity needs it.': 'لا شيء آخر لتعبئته ما لم يتطلبه هذا النشاط.',
    'Sign in, or check out as a guest with a one-time code.': 'سجّل الدخول، أو أكمل كضيف برمز لمرة واحدة.', 'Matchday help': 'مساعد يوم المباراة', 'Box office': 'شباك التذاكر', 'Concierge': 'الكونسيرج',
    'Museum guide': 'مرشد المتحف', 'Front desk': 'الاستقبال', 'Travel help': 'مساعد السفر', 'Cards and Apple Pay': 'البطاقات وApple Pay', 'Marketing, location, your data': 'التسويق والموقع وبياناتك',
    'Things you tapped the heart on': 'ما أعجبك', 'Upcoming and past, with receipts': 'القادمة والسابقة مع الإيصالات', '3 new': '3 جديدة', 'Codes and promotions': 'الرموز والعروض', 'Reserve and pay': 'احجز وادفع',
    'Report something': 'أبلغ عن شيء', 'Wheelchairs, quiet room, carers': 'الكراسي المتحركة والغرفة الهادئة والمرافقون', 'Two-step sign-in, Face Pass': 'الدخول بخطوتين وبصمة الوجه', 'Language': 'اللغة',
    'Chat, lost property, feedback': 'الدردشة والمفقودات والملاحظات', 'Switch venue app': 'تبديل تطبيق المكان', 'Mobile': 'الجوال', 'Saved guests': 'الضيوف المحفوظون', 'On this iPhone': 'على هذا الآيفون',
    'Add a card': 'أضف بطاقة', 'Gold membership': 'العضوية الذهبية', 'Annual renewal': 'تجديد سنوي', 'Change or cancel plan': 'تغيير الخطة أو إلغاؤها', 'Download my data': 'تنزيل بياناتي',
    'A copy by email within 48 hours': 'نسخة بالبريد خلال 48 ساعة', 'Leave the queue': 'غادر الطابور', 'Order something else': 'اطلب شيئًا آخر', 'Sign in or join': 'سجّل الدخول أو انضم', 'Change or cancel': 'تغيير أو إلغاء',
    'Done': 'تم', 'Report it': 'أبلغ', 'Back to home': 'العودة للرئيسية', 'Send rating': 'أرسل التقييم', 'See it on the map': 'اعرضه على الخريطة', 'Send ticket': 'أرسل التذكرة',
    'Enjoy the rest of the park while you wait. Only one virtual queue at a time.': 'استمتع ببقية المنتزه أثناء الانتظار. طابور افتراضي واحد في كل مرة.', 'Add something to your order to continue.': 'أضف شيئًا إلى طلبك للمتابعة.',
    'Offers apply at checkout automatically when you meet the conditions.': 'تُطبّق العروض تلقائيًا عند الدفع إذا استوفيت الشروط.', 'Free cancellation up to one hour before arrival.': 'إلغاء مجاني حتى ساعة قبل الوصول.',
    'Tap the heart on anything you like and it appears here.': 'اضغط على القلب في أي شيء يعجبك ليظهر هنا.', 'Choose a ride': 'اختر لعبة', 'Use your points': 'استخدم نقاطك', 'Today': 'اليوم', 'Upcoming': 'القادمة', 'Past': 'السابقة',
    'Popular': 'الأكثر طلبًا', 'Your cases': 'طلباتك', 'Where from': 'من أين', 'Pickup': 'الاستلام', 'Car park': 'الموقف', 'Arriving': 'الوصول', 'Try': 'جرّب', 'Show prices in': 'اعرض الأسعار بـ',
    'What would you like to do?': 'ماذا تريد أن تفعل؟', 'Remind me': 'ذكّرني', 'Menu': 'القائمة', 'For you': 'لك', 'How was it?': 'كيف كانت؟', 'What stood out?': 'ما الذي لفت انتباهك؟',
    'See live waits': 'عرض الانتظار المباشر', 'Reserve parking': 'احجز موقفًا', 'Report lost item': 'أبلغ عن مفقود', 'Ticket': 'تذكرة', 'Assistant': 'المساعد',
    'Freefall Tower has reopened': 'أعيد فتح برج السقوط الحر', 'Sunset Parade at 19:30': 'موكب الغروب الساعة 19:30', 'Summit Coaster wait over 25 min': 'انتظار Summit Coaster أكثر من 25 دقيقة',
    'Open now': 'مفتوح الآن', 'Match tonight': 'مباراة الليلة', 'Show tonight': 'عرض الليلة', 'Running': 'تعمل', 'Seats': 'المقاعد', 'Extras': 'الإضافات', 'Details': 'البيانات', 'Access': 'الوصول',
    'In 3 days': 'بعد 3 أيام', 'Used': 'مستخدمة', 'Best view from the plaza steps': 'أفضل مشهد من درجات الساحة', 'Try Junior Circuit, or add Fast Track': 'جرّب Junior Circuit أو أضف المسار السريع',
    'Your seats': 'مقاعدك', 'Nothing selected yet': 'لم تختر شيئًا بعد', 'Total to pay': 'المبلغ المستحق', 'Review and pay': 'راجع وادفع', 'You’re booked': 'تم حجزك', "You're booked": 'تم حجزك',
    'Rides': 'الألعاب', 'Dining': 'المطاعم', 'Shows': 'العروض', 'Shops': 'المتاجر', 'Slides': 'الزلاقات', 'Surf': 'ركوب الأمواج', 'Cabanas': 'الكابانات', 'Fixtures': 'المباريات', 'Store': 'المتجر',
    'Screenings': 'العروض السينمائية', 'Café': 'المقهى', 'Tables': 'الطاولات', 'Events': 'الفعاليات', 'Order': 'اطلب', 'Play': 'اللعب', 'Workshops': 'الورش', 'Parties': 'الحفلات', 'Visit': 'الزيارة',
    'Tours': 'الجولات', 'Rooms': 'الغرف', 'Routes': 'المسارات', 'Opening hours': 'ساعات العمل', 'Getting here': 'الوصول إلينا', 'Before you go': 'قبل أن تذهب', 'Swipe for photos': 'اسحب لرؤية الصور',
    'Hi, I’m Sahli. Ask me about tickets, waits, food, parking or anything at ': 'مرحبًا، أنا سهلي. اسألني عن التذاكر والانتظار والطعام والمواقف أو أي شيء في ',
    'How long are the queues?': 'كم مدة الانتظار؟', 'I’m hungry': 'أنا جائع', 'Where do I park?': 'أين أركن سيارتي؟', 'I lost something': 'فقدت شيئًا', 'Plan your trip': 'خطّط لرحلتك', 'Find a table': 'ابحث عن طاولة',
    'Pick your match time': 'اختر موعد المباراة', 'Choose a performance': 'اختر عرضًا', 'Choose a showtime': 'اختر موعد العرض', 'When, and for how long?': 'متى، ولكم من الوقت؟', 'When would you like to come?': 'متى تود الحضور؟',
    'Choose your tour': 'اختر جولتك', 'Pick a session': 'اختر جلسة', 'Guest checkout': 'الدفع كضيف', 'Sign in with email': 'الدخول بالبريد', 'Enter the six-digit code': 'أدخل الرمز المكوّن من ستة أرقام',
    'Send code': 'أرسل الرمز', 'Verify code': 'تحقق من الرمز', 'Email': 'البريد الإلكتروني', 'Full name': 'الاسم الكامل', 'Send request': 'أرسل الطلب', 'Request sent': 'تم إرسال الطلب',
    'Ask Sahli': 'اسأل سهلي', 'Ask Matchday help': 'اسأل مساعد المباراة', 'Ask Box office': 'اسأل شباك التذاكر', 'Ask Concierge': 'اسأل الكونسيرج', 'Ask Museum guide': 'اسأل مرشد المتحف', 'Ask Front desk': 'اسأل الاستقبال', 'Ask Travel help': 'اسأل مساعد السفر'
  };
  window.TV_AR_EXTRA = Object.assign(window.TV_AR_EXTRA || {}, A);
  window.TV_AR_RULES = (window.TV_AR_RULES || []).concat([
    [/^Step (\d+) of (\d+)$/, 'الخطوة $1 من $2'], [/^(\d+) to explore$/, '$1 للاستكشاف'], [/^Plan your visit · (\d) of 6$/, 'خطّط لزيارتك · $1 من 6'], [/^Pay AED ([\d,.]+)$/, 'ادفع $1 درهم'],
    [/^(.+) · Step (\d+) of (\d+)$/, '$1 · الخطوة $2 من $3'], [/^Day (\d) · (.+)$/, 'اليوم $1 · $2'], [/^(\d+) left$/, 'متبقٍ $1'], [/^Sold out$/, 'نفدت'], [/^New code in (\d+) s$/, 'رمز جديد خلال $1 ث'],
    [/^Section (.+)$/, 'القسم $1'], [/^Your seats: (.+)$/, 'مقاعدك: $1'], [/^Showing (\d+) of (\d+) that suit age (\d+)\.$/, 'نعرض $1 من $2 تناسب عمر $3.'], [/^(\d+) items?$/, '$1 عناصر'], [/^Chat with (.+)$/, 'تحدث مع $1']
  ]);
})();
