#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The audit decisions register: the 77 client questions from the Block A pull audit, and what was decided.

**Decided 28 September: every question takes our recommended default.** The client has not answered
them. Chinmay adopted the defaults so the build is not held on 77 open questions, and each one stays
open to the client's correction. So each row carries two things: what the package now does, and
who on the client side confirms it. A correction becomes a change request like any other.

Reads handoff/audit-decisions.json (the question pack, copied from the audit), writes
docs/registers/audit-decisions.md. A decision a later one replaced carries `superseded`, shown on its row.

**Rev 3 (29 September).** The client's rev 3 prototype feedback was decided point by point by Chinmay;
some of those answers replace an audit decision (R073 (c), R077 (a), R167 part 2, R242). They are read
from handoff/rev3-decisions.json and written to docs/registers/rev3-decisions.md by the same tool, so the
two registers cannot disagree about which decision stands.

    python3 tools/build-audit-decisions.py
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "handoff", "audit-decisions.json")
OUT = os.path.join(ROOT, "docs", "registers", "audit-decisions.md")


def cell(s):
    return " ".join(str(s or "").split()).replace("|", "\\|")


def main():
    rows = json.load(io.open(SRC, encoding="utf-8"))
    applied = sum(1 for r in rows if r.get("applied"))
    out = [
        "# Audit decisions",
        "",
        "> **Purpose:** the 77 questions the Block A pull audit raised for the client, and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/audit-decisions.json`",
        "",
        "**On 28 September every question took our recommended default.** The client has not answered them yet.",
        "Each default is what the package builds to from now on, and each stays open to the client's correction:",
        "a correction is raised as a change request, like any other.",
        "",
        f"**{len(rows)} decisions. {applied} applied to the package so far.** A decision is applied when every",
        "contract, state model, screen, table and document it touches says the same thing.",
        "",
        "| Id | Topic | Decision | Confirms | First release | Applied |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        out.append("| {} | {} | {} | {} | {} | {} |".format(
            r["id"], cell(r["theme"]), cell(r["default"]), cell(r["who"]),
            "yes" if str(r.get("first_release", "")).startswith("Yes") else "no",
            cell(r.get("applied") or "not yet") + (" · **superseded in part**" if r.get("superseded") else "")))
    out += ["", "## The questions in full", ""]
    for r in rows:
        out += [f"### {r['id']}: {r['theme']}", "",
                f"**Question.** {cell(r['question'])}", "",
                f"**Why it matters.** {cell(r.get('why'))}", "",
                f"**Blocks.** {cell(r.get('blocks'))}", "",
                f"**Decided (28 September, our recommendation).** {cell(r['default'])}", "",
                f"**Client confirms.** {cell(r['who'])}", ""]
        if r.get("superseded"):
            out += [f"**Superseded.** {cell(r['superseded'])}", ""]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} decisions, {applied} applied -> {os.path.relpath(OUT, ROOT)}")
    rev3()


KIND = {"conflict": "Conflicts with an earlier decision", "new-capability": "New capabilities",
        "contract": "Contract gaps", "config": "Settings", "screen": "Screens"}


def rev3():
    src = os.path.join(ROOT, "handoff", "rev3-decisions.json")
    out_path = os.path.join(ROOT, "docs", "registers", "rev3-decisions.md")
    rows = json.load(io.open(src, encoding="utf-8"))
    out = [
        "# Rev 3 decisions",
        "",
        "> **Purpose:** every point of the client's rev 3 prototype feedback (guest web and mobile booking), and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/rev3-decisions.json`",
        "",
        "**Decided 29 September by Chinmay, point by point.** The prototype and the client's responses are in",
        "`sources/designs/guest-rev3-28-september/`. Presentation-only points (layout that changes nothing in the",
        "package) are left out. Four answers replace an earlier audit decision: R073 (c), R077 (a), R167 part 2",
        "and R242, each marked superseded in [audit-decisions](audit-decisions.md).",
        "",
        f"**{len(rows)} decisions.**",
        "",
    ]
    for kind, title in KIND.items():
        rs = [r for r in rows if r["kind"] == kind]
        if not rs:
            continue
        out += [f"## {title} ({len(rs)})", "", "| Ref | What the prototype does | Decision | Screens |", "| --- | --- | --- | --- |"]
        out += ["| {} | {} | {} | {} |".format(r["ref"], cell(r["what"]), cell(r["decision"]),
                                             cell(", ".join(r.get("screens") or []))) for r in rs]
        out.append("")
    io.open(out_path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} rev 3 decisions -> {os.path.relpath(out_path, ROOT)}")


if __name__ == "__main__":
    main()
