#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write `handoff/api-list.md` from the contracts, instead of maintaining a copy of them.

**It was a hand-written duplicate of data the contracts already carry, and it drifted by a
factor of three.** On 19 September its header read "**581 published** — 211 spine, 346
satellite" and marked modules blocked; there were 1,974 operations across 32 contracts and
nothing blocked. It also carried a status key — published / specified / not specified —
that stopped meaning anything the moment the contracts became the source of truth. **If an
operation is in a contract it is published**; there is nowhere else for it to be.

Every column it held is a field on the operation:

    Method, Path      the path item itself
    Permission        x-ticvai-permission        1974 / 1974
    Audience          x-ticvai-audience          1974 / 1974
    Offline           x-ticvai-offline-capable   1639
    Consumers         x-ticvai-consumed-by       1786, written by link-screens-contracts

**That last one decides where this runs.** `link-screens-contracts.py` back-writes
`x-ticvai-consumed-by` into the contracts, and it runs after the screens. Generate this
file before that and every newly-wired operation shows no consumer for a whole cycle —
which is the silent staleness the file is being rescued from.

Reads nothing but `contracts/`. Writes one file. No `--apply`: it has no other mode.
"""
import collections
import glob
import io
import os
import re

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "handoff", "api-list.md")
VERBS = ("get", "post", "put", "patch", "delete")

# **The app a platform builds into, not a pretty name for the platform.** These are the
# `platform.app` values the screens declare, which are the `frontend/*.yaml` filenames —
# the package's own roster. The first cut wrote display names ("Venue POS", "Venue Mgmt")
# and broke the viewer's consumer layer, which matches this column against an app list.
#
# Several platforms share an app and that is correct: P08, P13 and P16 are three surfaces
# of `venue-management-web`, and P02 and P05 are the guest app on a phone and on a kiosk.
APPS = {
    "P01": "guest-web", "P02": "guest-app", "P04": "venue-pos", "P05": "guest-app",
    "P06": "venue-staff-app", "P07": "venue-scanner", "P08": "venue-management-web",
    "P09": "ticvai-web", "P10": "partner-web", "P11": "accreditation-web",
    "P12": "venue-support-web", "P13": "venue-management-web",
    "P14": "developer-portal-web", "P15": "kitchen-display",
    "P16": "venue-management-web", "P17": "signup-web",
}


def one_liner(info):
    """What the contract owns, in a sentence, taken from its own description.

    Every contract opens its description either with a bold claim or with a
    `## What this contract covers` heading followed by one. Both are the author's own
    summary, which beats anything derivable from the paths.
    """
    d = (info.get("description") or "").strip()
    for m in re.finditer(r"\*\*(.+?)\*\*", d, re.S):
        s = " ".join(m.group(1).split())
        if len(s) > 25:
            return s.rstrip(".") + "."
    for line in d.split("\n"):
        line = line.strip()
        if line and not line.startswith("#"):
            return " ".join(line.split())[:160]
    return info.get("title") or ""


def contracts():
    out = []
    for tier in ("spine", "satellite", "shared"):
        for f in sorted(glob.glob(os.path.join(ROOT, "contracts", tier, "*.yaml"))):
            d = yaml.safe_load(io.open(f, encoding="utf-8")) or {}
            ops = []
            for path, m in (d.get("paths") or {}).items():
                if not isinstance(m, dict):
                    continue
                for v, op in m.items():
                    if v in VERBS and isinstance(op, dict):
                        ops.append((v.upper(), path, op))
            ops.sort(key=lambda r: (r[1], r[0]))
            out.append((tier, os.path.basename(f), d.get("info") or {}, ops))
    return out


def consumers(op):
    """The apps that call it, from the screens that declare it.

    An operation with none is not broken — 188 of them are configuration a screen has not
    been drawn for yet — but it is worth being able to see at a glance, so it says so.
    """
    seen = []
    for c in (op.get("x-ticvai-consumed-by") or []):
        code = str(c).split()[0]
        name = APPS.get(code)
        if name and name not in seen:
            seen.append(name)
    return ", ".join(sorted(seen)) if seen else "—"


def main():
    data = contracts()
    total = sum(len(o) for _t, _f, _i, o in data)
    by_tier = collections.Counter()
    for tier, _f, _i, ops in data:
        by_tier[tier] += len(ops)

    L = ["# API list", "",
         "> **Every operation in the package, and which app calls it.**",
         "> Generated from `contracts/` by `tools/build-api-list.py` — **do not edit this file.**",
         "> An operation that is in a contract is published; there is no other state for it to "
         "be in.", "",
         "**%s operations across %d contracts** — %s in the spine, %s in satellites."
         % ("{:,}".format(total), len([1 for t, _f, _i, o in data if o]),
            "{:,}".format(by_tier["spine"]), "{:,}".format(by_tier["satellite"])), "",
         "`Offline` is `x-ticvai-offline-capable`: whether the operation may be served from a "
         "device that cannot reach the platform. `Consumers` is `x-ticvai-consumed-by`, written "
         "back into the contracts by `tools/link-screens-contracts.py` from the screens that "
         "declare the operation — so an operation with no consumer is one no screen has been "
         "drawn for yet.", "", "---", ""]

    # `contracts/shared/` holds common.yaml and permissions.yaml — vocabularies every
    # contract imports, with no paths of their own. They are contracts in the folder sense
    # and not in the "has an API" sense, so they get no section rather than an empty one.
    for tier in ("spine", "satellite", "shared"):
        rows = [r for r in data if r[0] == tier and r[3]]
        if not rows:
            continue
        L += ["## %s — %d contract(s), %d operation(s)"
              % (tier.capitalize(), len(rows), by_tier[tier]), ""]
        for _t, fname, info, ops in rows:
            L += ["### `%s` — %d operation(s)" % (fname, len(ops)), "",
                  one_liner(info), "",
                  "| Method | Path | Operation | Permission | Offline | Consumers |",
                  "|---|---|---|---|---|---|"]
            for verb, path, op in ops:
                L.append("| %s | `%s` | `%s` | `%s` | %s | %s |"
                         % (verb, path, op.get("operationId") or "—",
                            op.get("x-ticvai-permission") or "—",
                            "✓" if op.get("x-ticvai-offline-capable") else "—",
                            consumers(op)))
            L.append("")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("  api-list: %d operations, %d contracts -> handoff/api-list.md"
          % (total, len(data)))


if __name__ == "__main__":
    main()
