#!/usr/bin/env python3
"""Render handoff/backlog-clusters.json as docs/registers/clusters.md."""
import json, pathlib, sys

def main():
    root = pathlib.Path(__file__).resolve().parent.parent
    c = json.loads((root/'handoff/backlog-clusters.json').read_text())
    b = {e['id']: e for e in json.loads((root/'handoff/contract-backlog.json').read_text())['entries']}
    cl = sorted(c['clusters'], key=lambda x: -x['rowCitations'])
    L = ["# Backlog clusters", "",
         "**175 open backlog entries are far fewer than 175 decisions.** This register groups them by",
         "what one decision or one build would close. Generated by `tools/build-cluster-index.py`;",
         "edit `handoff/backlog-clusters.json`, never this file.", "",
         f"**{len(cl)} clusters covering {sum(x['entryCount'] for x in cl)} entries and "
         f"{sum(x['rowCitations'] for x in cl)} row citations · {len(c['unclustered'])} singletons.**", "",
         "| Cluster | Entries | Rows | Lanes | Conflicts |", "|---|---:|---:|---|---|"]
    for x in cl:
        L.append(f"| **{x['id']} {x['name']}** | {x['entryCount']} | {x['rowCitations']} | "
                 f"{', '.join(x['lanes'])} | {x['conflicts']} |")
    L += ["", "---", ""]
    for x in cl:
        L += [f"## {x['id']} — {x['name']}", "",
              f"**{x['entryCount']} entries · {x['rowCitations']} row citations · "
              f"{', '.join(x['contracts']) or '—'} · {x['conflicts']}**", "",
              f"**{x['what']}**", "", x['why'], "",
              "| Entry | Lane | What |", "|---|---|---|"]
        for i in x['entries']:
            e = b.get(i)
            if e: L.append(f"| {i} | {e['lane']} | {e['what']} |")
        L += [""]
    if c['unclustered']:
        L += ["## Singletons", "",
              "Entries that stand alone — each is its own small decision.", "",
              "| Entry | Lane | What |", "|---|---|---|"]
        for i in c['unclustered']:
            e = b.get(i)
            if e: L.append(f"| {i} | {e['lane']} | {e['what']} |")
        L += [""]
    out = root/'docs/registers/clusters.md'
    out.write_text("\n".join(L), encoding='utf-8')
    print(f"clusters.md: {len(cl)} clusters, {len(c['unclustered'])} singletons")
    return 0

if __name__ == '__main__':
    sys.exit(main())
