<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Ticvai.ControlPlane</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ticvai.Shared.Kernel/Ticvai.Shared.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>
</Project>
