#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The audit decisions register: the 77 client questions from the Block A pull audit, and what was decided.

**Decided 28 September: every question takes our recommended default.** The client has not answered
them. Chinmay adopted the defaults so the build is not held on 77 open questions, and each one stays
open to the client's correction. So each row carries two things: what the package now does, and
who on the client side confirms it. A correction becomes a change request like any other.

Reads handoff/audit-decisions.json (the question pack, copied from the audit), writes
docs/registers/audit-decisions.md.

    python3 tools/build-audit-decisions.py
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "handoff", "audit-decisions.json")
OUT = os.path.join(ROOT, "docs", "registers", "audit-decisions.md")


def cell(s):
    return " ".join(str(s or "").split()).replace("|", "\\|")


def main():
    rows = json.load(io.open(SRC, encoding="utf-8"))
    applied = sum(1 for r in rows if r.get("applied"))
    out = [
        "# Audit decisions",
        "",
        "> **Purpose:** the 77 questions the Block A pull audit raised for the client, and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/audit-decisions.json`",
        "",
        "**On 28 September every question took our recommended default.** The client has not answered them yet.",
        "Each default is what the package builds to from now on, and each stays open to the client's correction:",
        "a correction is raised as a change request, like any other.",
        "",
        f"**{len(rows)} decisions. {applied} applied to the package so far.** A decision is applied when every",
        "contract, state model, screen, table and document it touches says the same thing.",
        "",
        "| Id | Topic | Decision | Confirms | First release | Applied |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        out.append("| {} | {} | {} | {} | {} | {} |".format(
            r["id"], cell(r["theme"]), cell(r["default"]), cell(r["who"]),
            "yes" if str(r.get("first_release", "")).startswith("Yes") else "no",
            cell(r.get("applied") or "not yet")))
    out += ["", "## The questions in full", ""]
    for r in rows:
        out += [f"### {r['id']}: {r['theme']}", "",
                f"**Question.** {cell(r['question'])}", "",
                f"**Why it matters.** {cell(r.get('why'))}", "",
                f"**Blocks.** {cell(r.get('blocks'))}", "",
                f"**Decided (28 September, our recommendation).** {cell(r['default'])}", "",
                f"**Client confirms.** {cell(r['who'])}", ""]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} decisions, {applied} applied -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
