#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write `wireframes/LINKAGE.md` — how boards, screens and operations resolve to each other.

**The explanation was right and every number in it was seven times too small.** On 19
September it opened "The boards are 364 screens of design intent. The definitions are the
same 347 in YAML"; there were 2,427, all of them anchored. It also validated operations
"against 689" when there were 1,974, and its worked example named a screen and a stored
procedure nobody had checked in weeks.

So the prose stays here, in the tool, and every count is computed. **The worked example is
computed too** — picking a real screen with operations and a table each time beats a
hand-chosen one that quietly stops being true.

Reads `screens/`, `wireframes/` and `handoff/api-data-lineage.json`. Writes one file.
"""
import glob
import io
import json
import os
import re

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "wireframes", "LINKAGE.md")


def gather():
    lin = json.load(io.open(os.path.join(ROOT, "handoff", "api-data-lineage.json"),
                            encoding="utf-8"))
    n = dict(defined=0, anchored=0, with_ops=0, to_table=0, reaches=0)
    plats, example = set(), None
    for f in sorted(glob.glob(os.path.join(ROOT, "screens", "P*.yaml"))):
        d = yaml.safe_load(io.open(f, encoding="utf-8")) or {}
        p = d.get("platform") or {}
        plats.add(p.get("code"))
        n["reaches"] += len(p.get("reachesOtherPlatforms") or [])
        for s in d.get("screens") or []:
            n["defined"] += 1
            board = (s.get("wireframe") or {}).get("board")
            if board:
                n["anchored"] += 1
            ops = [a.get("operationId") for a in (s.get("apis") or []) if a.get("operationId")]
            if not ops:
                continue
            n["with_ops"] += 1
            v = lin.get(ops[0]) or {}
            reads, writes = v.get("reads") or [], v.get("writes") or []
            if any((lin.get(o) or {}).get("reads") or (lin.get(o) or {}).get("writes")
                   for o in ops):
                n["to_table"] += 1
            # One real screen that exercises the whole chain, for the worked example.
            if example is None and board and reads and writes and v.get("service"):
                example = dict(id=s["id"], name=s["name"], board=board, op=ops[0],
                               service=v["service"], reads=reads[:4], writes=writes[:2])
    ops_total = 0
    for f in glob.glob(os.path.join(ROOT, "contracts", "*", "*.yaml")):
        d = yaml.safe_load(io.open(f, encoding="utf-8")) or {}
        for _p, m in (d.get("paths") or {}).items():
            if isinstance(m, dict):
                ops_total += sum(1 for v in m
                                 if v in ("get", "post", "put", "patch", "delete"))
    boards = sorted(glob.glob(os.path.join(ROOT, "wireframes", "*.dc.html")))
    hrefs = 0
    for b in boards:
        hrefs += len(re.findall(r'href="[^"]+#',
                                io.open(b, encoding="utf-8", errors="replace").read()))
    return n, len([p for p in plats if p]), ops_total, len(boards), hrefs, example


def main():
    n, plats, ops_total, boards, hrefs, ex = gather()
    unanchored = n["defined"] - n["anchored"]
    no_ops = n["defined"] - n["with_ops"]

    ex_line = ""
    if ex:
        ex_line = ("`%s` is `%s %s`, which calls `%s`, which lives in `%s`, reads `%s` and "
                   "writes `%s`."
                   % (ex["board"], ex["id"], ex["name"], ex["op"], ex["service"],
                      "`, `".join(ex["reads"]), "`, `".join(ex["writes"])))

    L = ["# How the boards link to everything else", "",
         "> Generated by `tools/build-linkage.py` — **do not edit this file.** Every count "
         "below is computed from `screens/`, `wireframes/` and `handoff/api-data-lineage.json`.",
         "",
         "**{:,} screens are defined in YAML and {:,} carry a board anchor.** They resolve to "
         "each other in both directions, and a checker keeps them that way."
         .format(n["defined"], n["anchored"]),
         "", "## The chain", "",
         "    board anchor  --->  screen definition  --->  operations  --->  service",
         "                                                      |",
         "                                                      v",
         "                                                tables - stored procedure", ""]
    if ex_line:
        L += [ex_line, ""]
    L += ["## Where each link lives", "",
          "| Direction | Where |",
          "|---|---|",
          "| Screen -> board | `wireframe.board` on every screen: `wireframes/<file>#<id>` |",
          "| Platform -> board | `platform.wireframeBoard` |",
          "| Board -> screen | The anchor `id` on each frame, matched by id |",
          "| Screen -> operations | `apis[].operationId`, validated against {:,} |"
          .format(ops_total),
          "| Operation -> tables | `handoff/api-data-lineage.json` |",
          "| Screen -> everything | **`handoff/screen-index.json`** - the join, pre-computed |",
          "", "## The numbers", "",
          "| | |", "|---|---:|",
          "| Boards on disk | {:,} |".format(boards),
          "| Platforms | {} |".format(plats),
          "| Screens defined | {:,} |".format(n["defined"]),
          "| Screens with a board anchor | {:,} |".format(n["anchored"]),
          "| **Screens with no anchor** | **{:,}** |".format(unanchored),
          "| Screens declaring at least one operation | {:,} |".format(n["with_ops"]),
          "| Screens whose operations resolve to a table | {:,} |".format(n["to_table"]),
          "| Anchored links inside the boards | {:,} |".format(hrefs),
          "| Cross-platform reaches declared | {} |".format(n["reaches"]),
          "",
          "**{:,} screens declare no operation.** They are real screens with a purpose and "
          "nothing specified yet, and `screen-index.json` says so by returning empty arrays "
          "rather than guessing. **{:,} declare operations that reach no table** - mostly "
          "configuration reads served from a cache, and navigation screens that only route."
          .format(no_ops, n["with_ops"] - n["to_table"]),
          "", "## What the checker enforces", "",
          "`tools/check-wireframes.py`:", "",
          "- Every screen points at a board that exists, and at an anchor inside it. **A link "
          "to an anchor a board does not have is a click that silently does nothing**, which "
          "is worse than no link at all.",
          "- Every anchor in a board has a screen definition. A screen somebody drew and "
          "nobody specified is the gap this exercise was closing.",
          "- Every href inside the boards resolves - all {:,} of them, file and anchor both."
          .format(hrefs),
          "- A platform's board matches its code, so one platform's screens cannot point at "
          "another's board.",
          "", "## When a board is regenerated", "",
          "Anchors are derived from screen ids, so a regenerated board keeps working as long "
          "as the ids do. **Renaming a screen id breaks both directions**, and the checker "
          "will say which - run it after any board change.", ""]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("  linkage: %d screens, %d anchored, %d board(s) -> wireframes/LINKAGE.md"
          % (n["defined"], n["anchored"], boards))


if __name__ == "__main__":
    main()
