#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The readiness close-out register: every provisional operation we agreed on 29 September, and why.

**Asked for on 29 September, so every decision can be traced back.** That day Chinmay set the rule
that the readiness questions are ours to answer from the client's own material, and that only
make-or-break questions stay with the client. Four agents applied it to the 577 operations that had
waited a month for sign-off; this register is the record of what each one decided and on what
evidence, in one place a reviewer can read or search.

Reads handoff/readiness-closeout.json (consolidated from the close-out results) and writes
docs/registers/readiness-closeout.md. The contracts carry the same evidence on each operation as
`x-ticvai-agreed`, so the register and the contract cannot say different things about the source.

    python3 tools/build-closeout-register.py
"""
import collections
import io
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "handoff", "readiness-closeout.json")
OUT = os.path.join(ROOT, "docs", "registers", "readiness-closeout.md")
WHY = {"a": "law, a regulator or a third-party contract", "b": "a name, account or vendor only the client has",
       "c": "money the client's customers pay or are refunded"}


def cell(s):
    return " ".join(str(s or "").split()).replace("|", "\\|")


def source_kind(ev):
    """Which kind of source a closure rests on: the minutes, the pack only, or our build plan."""
    e = ev.lower()
    if re.search(r"\bmom\b|minutes", e) and "mom silent" not in e and "no promotions minutes" not in e:
        return "minutes and pack"
    if "build plan" in e:
        return "pack and our build plan"
    return "pack"


def main():
    d = json.load(io.open(SRC, encoding="utf-8"))
    closed, kept, added = d["closed"], d["kept"], d["addedOperations"]
    by_contract = collections.Counter(c["contract"] for c in closed)
    by_source = collections.Counter(source_kind(c["evidence"]) for c in closed)
    reshaped = sum(1 for c in closed if c.get("changed") and "agreed as drafted" not in c["changed"].lower())
    questions = collections.OrderedDict()
    for k in kept:
        questions.setdefault(cell(k["question"]).split(" — why")[0], []).append(k)

    out = [
        "# Readiness close-out",
        "",
        "> **Purpose:** every operation that waited for sign-off, what we decided on 29 September, and the evidence  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Record. Generated by `tools/build-closeout-register.py` from `handoff/readiness-closeout.json`",
        "",
        "## The decision",
        "",
        f"**{cell(d['rule'])}**",
        "",
        f"Decided by Chinmay on 29 September 2026. {len(closed) + len(kept)} operations had been drafted from the "
        "client's design packs and waited a month for a backend engineer to say \"yes, that is the shape\" "
        "(`tools/build-provisional-review.py`).",
        "",
        "## How it was done",
        "",
        "1. **One brief, one rule** (`audit/ticvai/steps/Q/BRIEF.md`). Sources, in authority order: the minutes "
        "(`sources/mom/`, digested in `sources/mom-decisions.json`), the RFP and requirements, then the design packs "
        "and boards. Decisions already taken (the 77 audit decisions, the rev 3 decisions) were followed, not reopened.",
        "2. **Four agents, one set of contracts each**, working at the same time:",
        "   - QA: access and approvals",
        "   - QB: catalogue and subscription",
        "   - QC: promotions and orders",
        "   - QD: marketing-crm",
        "",
        "   Each read every operation against its cited pack page and the minutes, fixed the shape where the evidence "
        "said so, then either agreed it or kept it open.",
        "3. **Agreeing an operation** removes `x-ticvai-provisional` and adds `x-ticvai-agreed: '29 September: <evidence>'`. "
        "The operation's description ends with an \"Agreed (decided 29 September, readiness close-out)\" paragraph saying "
        "what changed.",
        "4. **Keeping one open** leaves it provisional with `x-ticvai-make-or-break: '<question>'`.",
        "5. **Screens followed the contracts.** Summary tiles moved into `*Summary` schemas, filters became query "
        "parameters, and example values stopped being fields. About 1,300 screen bindings were repointed "
        "(group RB), and `check-bindings` ended better than before the close-out.",
        f"6. **Gaps the review found were filled:** {len(added)} operations were added, by groups K1, K2 and K3 "
        "from the Venue Management close-out, plus QD and the coordinator. Group BN bound them to their screens.",
        "7. **Checks** after each group: the YAML parses, line endings are kept, and `check-states`, `check-config-scope`, "
        "`check-bindings`, `check-screens` and `check-flows` pass. Then the full package refresh.",
        "",
        "The working files (briefs, per-group results, review packets, apply scripts) are in `audit/ticvai/steps/Q/` on "
        "the coordinator's machine. The step is logged as S006 in `audit/ticvai/steps.jsonl`.",
        "",
        "## Result",
        "",
        f"**{len(closed)} agreed, {len(kept)} kept open, {len(added)} operations added.** {reshaped} of the agreed "
        "operations had their shape corrected; the rest were agreed as drafted.",
        "",
        "| Contract | Agreed |",
        "| --- | ---: |",
    ]
    out += [f"| {c} | {n} |" for c, n in by_contract.most_common()]
    out += ["", "| What the agreement rests on | Operations |", "| --- | ---: |"]
    out += [f"| {k} | {n} |" for k, n in by_source.most_common()]
    out += [
        "",
        "Operations resting on the pack and our build plan are in areas the client never workshopped, or never "
        "minuted (for example promotions: the 3 September walkthrough has no minutes, and membership was never "
        "workshopped). Each one names its pack page and the neighbouring operation its shape follows.",
        "",
        "## Kept for the client: make-or-break only",
        "",
        "| Question | Why it cannot be ours | Operations |",
        "| --- | --- | --- |",
    ]
    for q, ks in questions.items():
        out.append(f"| {q} | ({ks[0]['why']}) {WHY.get(ks[0]['why'], '')} | {', '.join(sorted({k['op'] for k in ks}))} |")
    out += [
        "",
        "**Worth the client's attention, not blocking:** A/B price tests on live customers, and cooling-off rights after "
        "an auto-renewal charge, may touch UAE consumer law. Both are left to venue-configured policy with a person "
        "approving, so nothing is built that the client's counsel cannot switch off.",
        "",
        "## Every agreed operation",
        "",
    ]
    for contract in sorted(by_contract):
        rows = sorted((c for c in closed if c["contract"] == contract), key=lambda c: c["op"])
        out += [f"### {contract} ({len(rows)})", "", "| Operation | Evidence | What changed |", "| --- | --- | --- |"]
        out += [f"| `{c['op']}` | {cell(c['evidence'])} | {cell(c['changed']) or 'agreed as drafted'} |" for c in rows]
        out.append("")
    out += ["## Operations added", "", "| Operation | Contract | Added by | Screens |", "| --- | --- | --- | --- |"]
    out += [f"| `{a['op']}` | {a['contract']} | {a['group']} | {cell(', '.join(a.get('screens') or []))} |"
            for a in sorted(added, key=lambda a: (a["contract"], a["op"]))]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(f"{len(closed)} agreed, {len(kept)} kept, {len(added)} added -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
