#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The audit decisions register: the 77 client questions from the Block A pull audit, and what was decided.

**Decided 28 September: every question takes our recommended default.** The client has not answered
them. Chinmay adopted the defaults so the build is not held on 77 open questions, and each one stays
open to the client's correction. So each row carries two things: what the package now does, and
who on the client side confirms it. A correction becomes a change request like any other.

Reads handoff/audit-decisions.json (the question pack, copied from the audit), writes
docs/registers/audit-decisions.md. A decision a later one replaced carries `superseded`, shown on its row.

**Rev 3 (29 September).** The client's rev 3 prototype feedback was decided point by point by Chinmay;
some of those answers replace an audit decision (R073 (c), R077 (a), R167 part 2, R242). They are read
from handoff/rev3-decisions.json and written to docs/registers/rev3-decisions.md by the same tool, so the
two registers cannot disagree about which decision stands.

**POS v2 (1 October).** The eight decisions on the POS v2 build, approved by Chinmay as recommended,
are read from handoff/pos-v2-decisions.json and written to docs/registers/pos-v2-decisions.md.

**Decisions of 2 October.** Chinmay's answers to the open questions of 2 October (563 decisions, DEC-001 to
DEC-563, plus the later rounds that override them where they conflict) are read from
handoff/decisions-2-october.json and written to docs/registers/decisions-2-october.md, with every change
entry that cites a decision listed beside it (read from changes/entries/), so the package carries the
decision log and what applied each one. The same day's decisions amend rows of the registers above (R221,
R261, R098, R144, R205, REV3-2, POSV2-4) through their `superseded` field, and add POSV2-9 to POSV2-13.

**Guest-screen fixes (2 October).** Four decisions, "decided by Chinmay: fix before Block A starts", on the
staff content and missing public reads the process agents found on the guest screens, are read from
handoff/guest-fix-decisions.json and written to docs/registers/guest-fix-decisions.md.

    python3 tools/build-audit-decisions.py
"""
import collections
import io
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "handoff", "audit-decisions.json")
OUT = os.path.join(ROOT, "docs", "registers", "audit-decisions.md")


def cell(s):
    return " ".join(str(s or "").split()).replace("|", "\\|")


def main():
    rows = json.load(io.open(SRC, encoding="utf-8"))
    applied = sum(1 for r in rows if r.get("applied"))
    out = [
        "# Audit decisions",
        "",
        "> **Purpose:** the 77 questions the Block A pull audit raised for the client, and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/audit-decisions.json`",
        "",
        "**On 28 September every question took our recommended default.** The client has not answered them yet.",
        "Each default is what the package builds to from now on, and each stays open to the client's correction:",
        "a correction is raised as a change request, like any other.",
        "",
        f"**{len(rows)} decisions. {applied} applied to the package so far.** A decision is applied when every",
        "contract, state model, screen, table and document it touches says the same thing.",
        "",
        "| Id | Topic | Decision | Confirms | First release | Applied |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        out.append("| {} | {} | {} | {} | {} | {} |".format(
            r["id"], cell(r["theme"]), cell(r["default"]), cell(r["who"]),
            "yes" if str(r.get("first_release", "")).startswith("Yes") else "no",
            cell(r.get("applied") or "not yet") + (" · **superseded in part**" if r.get("superseded") else "")))
    out += ["", "## The questions in full", ""]
    for r in rows:
        out += [f"### {r['id']}: {r['theme']}", "",
                f"**Question.** {cell(r['question'])}", "",
                f"**Why it matters.** {cell(r.get('why'))}", "",
                f"**Blocks.** {cell(r.get('blocks'))}", "",
                f"**Decided (28 September, our recommendation).** {cell(r['default'])}", "",
                f"**Client confirms.** {cell(r['who'])}", ""]
        if r.get("superseded"):
            out += [f"**Superseded.** {cell(r['superseded'])}", ""]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} decisions, {applied} applied -> {os.path.relpath(OUT, ROOT)}")
    rev3()


KIND = {"conflict": "Conflicts with an earlier decision", "new-capability": "New capabilities",
        "contract": "Contract gaps", "config": "Settings", "screen": "Screens"}


def rev3():
    src = os.path.join(ROOT, "handoff", "rev3-decisions.json")
    out_path = os.path.join(ROOT, "docs", "registers", "rev3-decisions.md")
    rows = json.load(io.open(src, encoding="utf-8"))
    out = [
        "# Rev 3 decisions",
        "",
        "> **Purpose:** every point of the client's rev 3 prototype feedback (guest web and mobile booking), and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/rev3-decisions.json`",
        "",
        "**Decided 29 September by Chinmay, point by point.** The prototype and the client's responses are in",
        "`sources/designs/guest-rev3-28-september/`. Presentation-only points (layout that changes nothing in the",
        "package) are left out. Four answers replace an earlier audit decision: R073 (c), R077 (a), R167 part 2",
        "and R242, each marked superseded in [audit-decisions](audit-decisions.md).",
        "",
        f"**{len(rows)} decisions.**",
        "",
    ]
    for kind, title in KIND.items():
        rs = [r for r in rows if r["kind"] == kind]
        if not rs:
            continue
        out += [f"## {title} ({len(rs)})", "", "| Ref | What the prototype does | Decision | Screens |", "| --- | --- | --- | --- |"]
        # A later decision that replaced or re-read this one is shown on the row (added 30 September:
        # GAP-C3 by MOB-6, 23SEP-18 by W7, REV3-11 by W4, the flow settings by W12).
        out += ["| {} | {} | {} | {} |".format(
            r["ref"], cell(r["what"]),
            cell(r["decision"]) + (" **Superseded:** " + cell(r["superseded"]) if r.get("superseded") else ""),
            cell(", ".join(r.get("screens") or []))) for r in rs]
        out.append("")
    io.open(out_path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} rev 3 decisions -> {os.path.relpath(out_path, ROOT)}")
    pos_v2()


POS_KIND = {"new-screen": "New screens", "conflict": "Where v2 contradicts a decision", "screen": "Screens changed",
            "design-gap": "What the design must add or drop", "accept-v2": "Accepted as drawn in v2 (2 October)"}


def pos_v2():
    """**The POS v2 decisions (1 October).** The POS v2 build (ours, not client-approved) was imported
    as candidate frames on 1 October; Chinmay then approved all eight recommended decisions on what it
    does differently. Read from handoff/pos-v2-decisions.json, written to docs/registers/pos-v2-decisions.md."""
    src = os.path.join(ROOT, "handoff", "pos-v2-decisions.json")
    out_path = os.path.join(ROOT, "docs", "registers", "pos-v2-decisions.md")
    rows = json.load(io.open(src, encoding="utf-8"))
    out = [
        "# POS v2 decisions",
        "",
        "> **Purpose:** what the POS v2 build does differently from the package, and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/pos-v2-decisions.json`",
        "",
        "**Decided 1 October by Chinmay: all eight recommendations approved.** The POS v2 build",
        "(`sources/designs/TICVAI_POS_Terminal_v2.html`, in git since 2 October: CHG-DOC-002) is our improved",
        "version of the client-approved terminal and the client has not approved it; its captures are in",
        "`wireframes/incoming/P04-pos-v2/`. The frames and their design corrections are applied by",
        "`tools/applied/pos-v2-decisions-1-october.py`; the specification changes are in the screens and",
        "contracts named below, and reach the tasks at the release refresh (r2).",
        "",
        "**Decided 2 October by Chinmay: the five candidates left undecided are accepted as drawn in v2**",
        "(POSV2-9 to POSV2-13: POS-000, POS-003, POS-004, POS-012, POS-023; DEC-550 to DEC-554 in",
        "[decisions-2-october](decisions-2-october.md)). A later decision that replaces part of a row is shown on it.",
        "",
        f"**{len(rows)} decisions.**",
        "",
    ]
    for kind, title in POS_KIND.items():
        rs = [r for r in rows if r["kind"] == kind]
        if not rs:
            continue
        out += [f"## {title} ({len(rs)})", "",
                "| Ref | What the v2 build does | Decision | Where it is applied | Screens |",
                "| --- | --- | --- | --- | --- |"]
        out += ["| {} | {} | {} | {} | {} |".format(
            r["ref"], cell(r["what"]),
            cell(r["decision"]) + (" **Superseded in part:** " + cell(r["superseded"]) if r.get("superseded") else ""),
            cell(r.get("applied")), cell(", ".join(r.get("screens") or []))) for r in rs]
        out.append("")
    io.open(out_path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} POS v2 decisions -> {os.path.relpath(out_path, ROOT)}")
    guest_fix()


GUEST_KIND = {"contract": "Contract: public reads for the guest surfaces", "screen": "Screens: staff content off the guest surfaces"}


def guest_fix():
    """**The guest-screen fixes (2 October).** The process agents' design notes of 1 October found staff content
    on the guest screens and two reads a visitor could not make; Chinmay decided to fix them before any Block A
    ticket starts. Read from handoff/guest-fix-decisions.json, written to docs/registers/guest-fix-decisions.md."""
    src = os.path.join(ROOT, "handoff", "guest-fix-decisions.json")
    out_path = os.path.join(ROOT, "docs", "registers", "guest-fix-decisions.md")
    rows = json.load(io.open(src, encoding="utf-8"))
    out = [
        "# Guest-screen fix decisions",
        "",
        "> **Purpose:** the staff content and the missing public reads found on the guest screens, and what was decided  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/guest-fix-decisions.json`",
        "",
        "**Decided 2 October 2026 by Chinmay: fix before Block A starts.** The process agents' design notes of",
        "1 October (`handoff/design-notes/white-label.yaml`, `ticketing-guest.yaml`, `finance-insights.yaml`) found",
        "that a first-time visitor could not load the tenant's theme or read a policy, and that the guest web (P01),",
        "app (P02) and kiosk (P05) screens still carried staff filters, raw tables, raw request forms and staff",
        "operations. The contract changes are additive (four public `/storefront/...` reads in",
        "`contracts/satellite/white-label.yaml`); the screens and flows are changed by",
        "`tools/applied/guest-screen-fixes-2-october.py`. The typed checks of the council of 2 October then found",
        "84 guest operations whose security admitted no guest and 200 pre-sign-in loads that needed a session:",
        "published reads were opened to visitors and personal screens declare sign-in",
        "(`tools/applied/guest-public-reads-2-october.py`, `guest-signin-declarations-2-october.py`; CHG-GST-001",
        "to 006). The new operations reach the tasks at the next refresh.",
        "",
        f"**{len(rows)} decisions.**",
        "",
    ]
    for kind, title in GUEST_KIND.items():
        rs = [r for r in rows if r["kind"] == kind]
        if not rs:
            continue
        out += [f"## {title} ({len(rs)})", "",
                "| Ref | What was found | Decision | Where it is applied | Screens |",
                "| --- | --- | --- | --- | --- |"]
        out += ["| {} | {} | {} | {} | {} |".format(
            r["ref"], cell(r["what"]), cell(r["decision"]), cell(r.get("applied")),
            cell(", ".join(r.get("screens") or []))) for r in rs]
        out.append("")
    io.open(out_path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} guest-fix decisions -> {os.path.relpath(out_path, ROOT)}")
    decisions_2_october()


DEC_REF = re.compile(r"\b((?:DEC-\d{3})|(?:DOOR|PRE)-\d+)\b")
CHG_ID = re.compile(r"^id:\s*'?(CHG-[A-Z]{2,6}-\d{3})'?\s*$", re.M)
STATUS = {"to-apply": "decided", "already-applied": "already applied", "needs-research": "**open: research first**",
          "needs-client": "**open: needs the client**"}
PROCESS_ORDER = ["AI", "Platform foundation", "Ticketing (back office)", "Ticketing (guest)", "White label & CMS",
                 "Customer & marketing", "F&B & retail", "Venue operations", "Finance & insights"]
OTHER = "Other decisions (no workbook row)"


def citing_entries():
    """Every change entry that cites a decision id, so the register shows what applied each one. A generator
    rule, not a hand-kept column: an entry that names `DEC-064` in its decision, why or notes is listed beside
    DEC-064 at the next run (CHG-DOC-019)."""
    out = {}
    d = os.path.join(ROOT, "changes", "entries")
    if not os.path.isdir(d):
        return out
    for name in sorted(os.listdir(d)):
        if not name.endswith(".yaml"):
            continue
        text = io.open(os.path.join(d, name), encoding="utf-8").read()
        m = CHG_ID.search(text)
        cid = m.group(1) if m else name[:12]
        is_open = re.search(r"^status:\s*open\s*$", text, re.M) is not None
        for ref in sorted(set(DEC_REF.findall(text))):
            out.setdefault(ref, []).append(cid + (" (open)" if is_open else ""))
    return out


def decisions_2_october():
    """**The decisions of 2 October.** Chinmay answered every open question of the process design notes on
    2 October (batches 1 to 6, the critical sets, AI residency, PII scrubbing, the cookie scanner, domains,
    POS v2, the rules decisions), then a door follow-up and a pre-apply round that override the earlier rows
    where they conflict. The log lived in the audit working folder, outside git; this register is the
    package's copy. Read from handoff/decisions-2-october.json, written to docs/registers/decisions-2-october.md."""
    src = os.path.join(ROOT, "handoff", "decisions-2-october.json")
    out_path = os.path.join(ROOT, "docs", "registers", "decisions-2-october.md")
    if not os.path.exists(src):
        return
    doc = json.load(io.open(src, encoding="utf-8"))
    rows, later, amends = doc["decisions"], doc.get("later_rounds") or [], doc.get("amends") or []
    by_ref = citing_entries()
    unmarked = amendments_marked(amends)

    def applied(r):
        got = list(r.get("applied_by") or []) + by_ref.get(r["id"], [])
        return ", ".join(dict.fromkeys(got)) or "not yet"

    counts = collections.Counter(r["status"] for r in rows)
    reviewable = sum(1 for r in rows if r.get("reviewable"))
    out = [
        "# Decisions of 2 October 2026",
        "",
        "> **Purpose:** every decision Chinmay took on 2 October on the open questions, with what was decided and why  ",
        "> **Owner:** Chinmay  ",
        "> **Status:** Living. Generated by `tools/build-audit-decisions.py` from `handoff/decisions-2-october.json`",
        "",
        "**Decided 2 October 2026 by Chinmay.** The process design notes (`handoff/design-notes/*.yaml`) carried",
        "538 open questions, each with a drawn default; Chinmay answered them in six batches and three critical",
        "sets, and took the AI residency, PII scrubbing, cookie scanner, domain and POS v2 decisions the same day.",
        "His words are in [answers-2-october](../active/decisions/answers-2-october.md) (later sections override",
        "earlier ones); the non-critical questions he did not review took their drawn default and are listed in",
        "[questions-defaults-to-review](../active/decisions/questions-defaults-to-review.md); the research cited is in",
        "`docs/active/research/`. **A row is applied when a change entry citing its id is listed in the last",
        "column** (read from `changes/entries/` at each run; \"(open)\" means the entry is not closed yet).",
        "",
        "**{} decisions** ({} decided, {} already applied before 2 October, {} waiting on research, {} waiting on"
        " the client or a vendor), **{} taken as the drawn default without review** (marked *reviewable*:"
        " Chinmay may still overrule one before its block is broken into tasks), and **{} later-round decisions**"
        " that override them where they conflict.".format(
            len(rows), counts.get("to-apply", 0), counts.get("already-applied", 0), counts.get("needs-research", 0),
            counts.get("needs-client", 0), reviewable, len(later)),
        "",
        "## What these decisions change in earlier decisions ({})".format(len(amends)),
        "",
        "| Earlier decision | Where it is recorded | What changes | Decided by |",
        "| --- | --- | --- | --- |",
    ]
    out += ["| {} | {} | {} | {} |".format(cell(a["ref"]), cell(a["where"]), cell(a["change"]), cell(", ".join(a["by"])))
            for a in amends]
    out += ["", "## The later rounds: they override the rows below where they conflict ({})".format(len(later)), "",
            "| Ref | Round | Topic | Decision | Why | Overrides | Applied by |", "| --- | --- | --- | --- | --- | --- | --- |"]
    out += ["| {} | {} | {} | {} | {} | {} | {} |".format(
        r["id"], cell(r["source"]), cell(r["topic"]), cell(r["decision"]), cell(r["why"]),
        cell(", ".join(r.get("overrides") or [])) or "—", cell(applied(r))) for r in later]
    out.append("")
    groups = collections.OrderedDict((p, []) for p in PROCESS_ORDER)
    groups[OTHER] = []
    for r in rows:
        groups.setdefault(r.get("process") or OTHER, []).append(r)
    for title, rs in groups.items():
        if not rs:
            continue
        out += ["## {} ({})".format(title, len(rs)), "",
                "| Id | Screen | Block | Decision | Why | Status | Applied by |",
                "| --- | --- | --- | --- | --- | --- | --- |"]
        for r in sorted(rs, key=lambda r: (str(r.get("block") or "Z"), r["id"])):
            dec = cell(r["decision"])
            if r.get("overridden_by"):
                dec += " **Overridden in part by " + ", ".join(r["overridden_by"]) + "** (later round, above)."
            if r.get("ambiguity"):
                dec += " *Note:* " + cell(r["ambiguity"])
            status = STATUS.get(r["status"], r["status"]) + (" · *reviewable*" if r.get("reviewable") else "")
            out.append("| {} | {} | {} | {} | {} | {} | {} |".format(
                r["id"], cell(r.get("screen")) or "—", cell(r.get("block")) or "—", dec, cell(r["why"]), status,
                cell(applied(r))))
        out.append("")
    io.open(out_path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} decisions of 2 October, {len(later)} later-round -> {os.path.relpath(out_path, ROOT)}")
    if unmarked:
        for u in unmarked:
            print("  NOT MARKED  " + u)
        raise SystemExit("%d earlier decision(s) amended on 2 October carry no mark in their own register" % len(unmarked))


AMEND_SOURCES = (
    (re.compile(r"^R\d{3}$"), "audit-decisions.json", "id", ("superseded",)),
    (re.compile(r"^REV3-\d+$"), "rev3-decisions.json", "ref", ("superseded",)),
    (re.compile(r"^POSV2-\d+$"), "pos-v2-decisions.json", "ref", ("superseded", "decision")),
    (re.compile(r"^AI-D\d+$"), "ai-decisions.json", "id", ("amended",)),
)


def amendments_marked(amends):
    """**An earlier decision a later one amends carries the mark in its own register** (CHG-DOC-012 to 017).
    A register row that still reads as the decision in force after it was amended is the 'package contradicts
    a decision' class: a reader of audit-decisions.md would build R221's fixed direction after 2 October said
    it switches live. So every `amends` row of decisions-2-october.json that names an audit root, a rev 3 point,
    a POS v2 decision or an AI decision must find that row in its own JSON with a `superseded` (or `amended`)
    field that cites one of the deciding ids. The generator refuses to finish otherwise."""
    loaded, problems = {}, []
    for a in amends:
        refs = re.findall(r"\b(R\d{3}|REV3-\d+|POSV2-\d+|AI-D\d+)\b", a["ref"])
        for ref in refs:
            for pat, fname, key, fields in AMEND_SOURCES:
                if not pat.match(ref):
                    continue
                if fname not in loaded:
                    data = json.load(io.open(os.path.join(ROOT, "handoff", fname), encoding="utf-8"))
                    loaded[fname] = data["decisions"] if isinstance(data, dict) else data
                row = next((r for r in loaded[fname] if r.get(key) == ref), None)
                if row is None:
                    if "(new)" not in a["ref"]:
                        problems.append(f"{ref}: not found in handoff/{fname}")
                    break
                marks = " ".join(json.dumps(row.get(f), ensure_ascii=False) for f in fields if row.get(f))
                if not any(b in marks for b in a["by"]):
                    problems.append(f"{ref} (handoff/{fname}): no {'/'.join(fields)} citing {', '.join(a['by'])}")
                break
    return problems


if __name__ == "__main__":
    main()
